---
title: "lab_2"
author: "Chris Samoray"
date: "2022-08-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
library(plotly)
library(widgetframe)
library(leaflet)
library(sf)
library(rgeos)
library(tigris)
library(rgdal)
options(tigris_use_cache = TRUE)
```

## R Markdown
```{r}
ozone.df <- read_csv("./data/daily_44201_2017.csv") # load data

names(ozone.df)
names(ozone.df) <- gsub(" ", "_", names(ozone.df)) # remove spaces

ozone.df$stcofips <- paste(formatC(ozone.df$State_Code, width = 2, flag = "0"), formatC(ozone.df$County_Code, width = 3, flag = "0"), sep = "") 
head(ozone.df$stcofips) #combine state and county fips, flag for leading 0

ozone.df.subset <- ozone.df[ , c('stcofips', 'Site_Num', 'Latitude', 'Longitude', 'Date_Local', 'State_Name', 'County_Name', 'CBSA_Name', 'AQI')]

nrow(unique(ozone.df.subset[ , c("Longitude", "Latitude")])) # select unique longlat

ozone.df.subset$stcofips %>% unique() %>% length()

# ozone.df.test <- select(ozone.df, ends_with(Name)) # this does not work
```


```{r}
##### EXERCISE 1 #####

test <- ozone.df.subset %>% select(stcofips, Date_Local, AQI) %>% arrange(stcofips, desc(Date_Local)) 

test2 <- test %>% top_n(10)


#convert to radians
ozone.df.subset <- mutate(ozone.df.subset, Latitude_rad = pi * Latitude / 180, 
                        Longitude_rad = pi * Longitude / 180)

# unique ID for monitoring station
ozone.df.subset <- mutate(ozone.df.subset, SiteID = paste(stcofips, Site_Num, sep="_"))
```


```{r}
##### EXERCISE 2 #####

dist.fcn <- function(lat1, lon1) {
   
  lat2 <- 39.8333333 / 180 * pi
  lon2 <- -98.585522 / 180 * pi
    
  outcome <- atan(((cos(lat2) * sin(lon2-lon1))^2) + (cos(lat1) * sin(lat2) - sin(lat1)*cos(lat2)*cos(lon2-lon1))^2)^.5 / (sin(lat1)*sin(lat2) + cos(lat1)*cos(lat2)*cos(lon2-lon1)) 

  return(outcome)
}
  
ozone.df.subset$dist_center <- dist.fcn(ozone.df.subset$Latitude_rad, ozone.df.subset$Longitude_rad) * 6371 # make sure to use radians
```


```{r}
group_by(ozone.df.subset, SiteID) %>% filter(n() < 30)

group_by(ozone.df.subset, stcofips, Date_Local) %>% summarise(maxAQI = max(AQI))

county_summary_df <- ozone.df.subset %>% 
  group_by(stcofips, Date_Local) %>%
  summarize(maxAQI=max(AQI),
            State_Name=first(State_Name),
            County_Name=first(County_Name), 
            CBSA_Name=first(CBSA_Name)) %>%
  group_by(stcofips) %>%
  summarize(AQIgt100 = sum(maxAQI>=100), 
            numDays= n(), 
            percAQIgt100 = AQIgt100/numDays, 
            State_Name=first(State_Name), 
            County_Name=first(County_Name), 
            CBSA_Name=first(CBSA_Name)
            )

county_summary_df
```

```{r}
##### EXERCISE 3 #####
state_summary_df <- ozone.df.subset %>% 
  mutate(month = lubridate::month(Date_Local)) %>% # for correct date format and select just month
  group_by(State_Name, month) %>% 
  summarize(numDays = n(),
            AQIgt100 = sum(AQI>=100),
            percAQIgt100 = AQIgt100/numDays,
            State_Name=first(State_Name))

cbsa_summary_df <- ozone.df.subset %>% 
  mutate(month = lubridate::month(Date_Local)) %>% 
  group_by(CBSA_Name, month) %>% 
  summarize(numDays = n(),
            AQIgt100 = sum(AQI>=100),
            percAQIgt100 = AQIgt100/numDays,
            CBSA_Name=first(CBSA_Name))

```
```{r}
g1 <- ozone.df.subset %>% 
  filter(stcofips == "06059") %>% # Orange County
  ggplot() + 
  geom_point(aes(x=Date_Local, y=AQI, color=SiteID)) +
  geom_smooth(aes(x=Date_Local, y=AQI, color=SiteID), method="loess")+
  scale_colour_brewer(palette = "Set2") + 
  labs(x = "Month", y = "Air Quality Index")

g1


ggplotly(g1)

ozone.df.subset %>% 
  filter(stcofips == "06059") %>% # Orange County
  ggplot() + 
  coord_polar(theta = "x")+
  geom_point(aes(x=Date_Local, y=AQI, color=SiteID)) +
  geom_smooth(aes(x=Date_Local, y=AQI, color=SiteID), method="loess")+
  scale_colour_brewer(palette = "Dark2") + 
  labs(x = "Month", y = "Air Quality Index")


ozone.df.subset %>% 
  filter(State_Name == "California") %>% 
  ggplot() + 
  geom_smooth(aes(x=Date_Local, y=AQI, color=SiteID), method="loess",  se=FALSE)+
  scale_colour_grey(end = 0)+
  facet_wrap(~stcofips)+
  labs(x = "Month", y = "Air Quality Index") + 
  theme_bw() + 
  theme(axis.text.x=element_blank(),
        legend.position="none")

```
```{r}
##### EXERCISE 4 #####

ozone.df.subset <- ozone.df.subset %>% 
  mutate(month = lubridate::month(Date_Local))

ozone.df.subset %>% 
  filter(State_Name == "California" & month > 5 & month < 9) %>% # summer months
  ggplot() + 
  geom_smooth(aes(x=Date_Local, y=AQI, color=SiteID), method="loess",  se=FALSE)+
  scale_colour_grey(end = 0)+
  facet_wrap(~CBSA_Name)+ # facet by CBSA 
  labs(x = "Month", y = "Air Quality Index") + 
  theme_bw() + 
  theme(axis.text.x=element_blank(),
        legend.position="none")
```

```{r}
g1 <- ozone.df.subset %>% 
  filter(State_Name == "California")  %>% 
  ggplot() + 
  geom_smooth(aes(x=Date_Local, y=AQI, group=SiteID, color=stcofips), method="loess", se=FALSE)+
  labs(x = "Month", y = "Air Quality Index") + 
  theme_bw() 

ggplotly(g1)

g1 <- ozone.df.subset %>% 
  filter(stcofips == "06037") %>% 
  ggplot() + 
  geom_point(aes(x=Site_Num, y=AQI), show.legend = F)+
  stat_summary(aes(x=Site_Num, y=AQI), fun='median', colour = "red", size = 1)+
  stat_summary(aes(x=Site_Num, y=AQI),fun='mean', colour = "green", size = 1, shape=3)+
  labs(x = "Site", y = "Air Quality Index", title="Los Angeles County") + 
  theme_bw() 

g1



g1 <- ozone.df.subset %>% 
  filter(stcofips == "06037") %>% 
  ggplot() + 
  geom_violin(aes(x=Site_Num, y=AQI), show.legend = F, 
              draw_quantiles = c(.25, .75) )+ # add quantiles
  stat_summary(aes(x=Site_Num, y=AQI), fun='median', colour = "red", size = 1)+
  stat_summary(aes(x=Site_Num, y=AQI),fun='mean', colour = "green", size = 1, shape=3)+
  labs(x = "Site", y = "Air Quality Index", title="Los Angeles County") + 
  theme_bw() 

g1


g2 <- county_summary_df %>%
  top_n(25, percAQIgt100) %>%
  ggplot()+
  geom_col(aes(x=reorder(paste(County_Name, State_Name, sep=","), percAQIgt100), y=percAQIgt100, fill=State_Name)) + 
  scale_fill_brewer(palette = "Accent", name="State") + # change color
  coord_flip()+
  labs(y="Proportion of days with Ozone AQI greater than 100", x="County", Title="Top 25 polluted counties")+
  theme_minimal()

ggplotly(g2, tooltip = c("y"))
```
```{r}
monitorlocations_df <- unique(ozone.df.subset[,c('Longitude', 'Latitude')]) 

m <-  leaflet(monitorlocations_df) %>%
  addProviderTiles(providers$Stamen.TonerLines, group = "Basemap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Basemap") %>%
  addCircles(group = "Monitors")%>%
  addLayersControl(
    overlayGroups = c("Monitors", 'Basemap'),
    options = layersControlOptions(collapsed = FALSE)
      )

widgetframe::frameWidget(m, height = 350, width = '95%')
```


```{r}
m %>%   
  addMarkers(clusterOptions = markerClusterOptions(), group = "Monitors") %>%
   frameWidget(height = 350, width = '95%')

ctys_shp <- counties(cb=TRUE, progress_bar = FALSE) #Only generalised boundaries are required

names(ctys_shp)

ctys_shp <- inner_join(ctys_shp, county_summary_df, by =c("GEOID"='stcofips')) 

nrow(ctys_shp)
st_crs(ctys_shp)
ctys_shp <- st_transform(ctys_shp, crs =4326)

Qpal <- colorQuantile(
  palette = "YlOrRd", n = 5, # change color
  domain = ctys_shp$percAQIgt100[ctys_shp$percAQIgt100>0]
)


labels <- sprintf(
  "County: %s <br/> AQI>100 days: <strong>%s</strong> %%",
  paste(ctys_shp$County_Name, ctys_shp$State_Name, sep=","),prettyNum(ctys_shp$percAQIgt100*100, digits=2)
) %>% lapply(htmltools::HTML)

m <-  leaflet(ctys_shp) %>%
  addProviderTiles(providers$Stamen.TonerLines, group = "Basemap") %>%
   addProviderTiles(providers$Stamen.TonerLite, group = "Basemap") %>%
       addPolygons(color = "#CBC7C6", weight = 2.5, smoothFactor = 0.5, # change line weight
              opacity = 1.0, fillOpacity = 0.5,
             fillColor = Qpal(ctys_shp$percAQIgt100),
              highlightOptions = highlightOptions(color = "green", weight = 2, bringToFront = TRUE),
             label = labels,
             labelOptions = labelOptions(
               style = list("font-weight" = "normal", padding = "3px 8px"),
               textsize = "15px",
               direction = "auto"),
             group = "Counties"
             )%>%
  addCircles(data=monitorlocations_df, group = 'Monitors') %>% 
  addLayersControl(
    overlayGroups = c("Counties", 'Basemap', 'Monitors'),
    options = layersControlOptions(collapsed = FALSE)
      )


 m %>%  addMarkers(data = monitorlocations_df, clusterOptions = markerClusterOptions(), group = "Monitors")
```

