---
title: "hw3"
author: "Chris Samoray"
date: "2022-09-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(lubridate)
library(ggplot2)
library(leaflet)
```

```{r, load and clean data, include=F}
nyc.crash <- read_csv(here("hw3", "data", "Motor_Vehicle_Collisions_Crashes.csv"))

glimpse(nyc.crash)
head(nyc.crash)
names(nyc.crash)

# keep only observations w/geographic info
nyc.crash.slim <- nyc.crash %>% filter(!is.na(LATITUDE) & !is.na(LONGITUDE))

# there are some obviously wrong longlats; filter
summary(nyc.crash$LONGITUDE)
summary(nyc.crash$LATITUDE)

nyc.crash.slim <- nyc.crash.slim %>% filter(LATITUDE > 40 & LATITUDE < 41 & LONGITUDE < -73 & LONGITUDE > -75)
                                            

# get rid of space in variable names
names(nyc.crash.slim) <- gsub(" ", "_", names(nyc.crash.slim)) 

# make data variable a date
nyc.crash.slim$CRASH_DATE <- mdy(nyc.crash.slim$CRASH_DATE)

```

```{r, crashes by borough}
# first determine which borough has most crashes
# observations with NA borough were removed, but they can be geolocated and appear in subsequent analyses
nyc.crash.slim %>% group_by(BOROUGH) %>% filter(!is.na(BOROUGH)) %>% summarise(crash_count = n()) %>% 
  ggplot(aes(x=reorder(BOROUGH, crash_count), y = crash_count)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Traffic Collisions by Borough in NYC", y = "Number of Collisions", x = "Borough")+
  theme_classic()

# how does crash fluctuate over year?
nyc.crash.slim <- nyc.crash.slim %>% mutate(month = month(CRASH_DATE))

g1 <- nyc.crash.slim %>% group_by(BOROUGH, month) %>% filter(!is.na(BOROUGH)) %>% 
  summarise(crash_count = n()) %>% 
  ggplot(aes(x = month, y = crash_count))+
  geom_smooth(method = "loess", se = F)+
  scale_x_continuous(name="Month", breaks = 1:12)+
  theme_bw()+
  theme()

g1+facet_wrap(~BOROUGH)
```


```{r, Brooklyn Analysis}

brooklyn.df <-  nyc.crash.slim %>% filter(BOROUGH == "BROOKLYN")  

brooklyn.df %>% 
  group_by(month) %>% 
  summarise(crashes.month = n()) %>% 
  arrange(desc(crashes.month)) # July is month with most crashes

brooklyn.loc <- brooklyn.df %>% filter(month == "7") %>% 
  group_by(LOCATION) %>% 
  summarise(crash = n(),
            lat = first(LATITUDE),
            long = first(LONGITUDE)) %>% 
  top_n(100, crash) # 100 locs with most crashes in July

leaflet(brooklyn.loc) %>% 
  addCircles() %>% 
  addProviderTiles(providers$Stamen.TonerLines, group = "Basemap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Basemap")
  

locs <- brooklyn.loc$LOCATION

brooklyn.car <- brooklyn.df %>% filter(LOCATION %in% locs)

ggplot(brooklyn.car, aes(x=, y = crash_count)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  labs(title = "Traffic Collisions by Borough in NYC", y = "Number of Collisions", x = "Borough")+
  theme_classic()

brooklyn.car <- brooklyn.car %>% 
  mutate(day = wday(CRASH_DATE),
         time = hour(CRASH_TIME))
# then do same, but show difference by injured, killed or neither
# time of day, day of week




```

