---
title: "hw2"
author: "Chris Samoray"
date: "9/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)

library(tidyverse)
library(here)
library(leaflet)
library(widgetframe)
```

```{r, echo=F, warning=F, include=F}
# load NO2 & O3 data from 2021
no2.df <- read_csv(here("HW_2", "data", "daily_42602_2021.csv"))

o3.df <- read_csv(here("HW_2", "data", "daily_44201_2021.csv"))


##############
# clean data
##############

# what does data look like?
glimpse(no2.df) 
glimpse(o3.df) 

# function to clean datasets
aqi.fcn <- function(x){
  
# remove spaces in column names
names(x) <- gsub(" ", "_", names(x)) 

# create new column of state/co fips code
x$stcofips <- paste(formatC(x$State_Code, width = 2, flag = "0"), formatC(x$County_Code, width = 3, flag = "0"), sep = "") # flag searches for leading zeros

print(x$stcofips %>% unique() %>% length()) # how many counties included
print(unique(nchar(x$stcofips))) # all have fips with 5 numbers

# select columns of interest
x <- x %>% select(stcofips, State_Name, County_Name, CBSA_Name, Site_Num, Longitude, Latitude, Date_Local, AQI, Parameter_Name)

x <- x %>%  mutate(month = substr(Date_Local, 6, 7))
 
return(x)
}

no2.df <- aqi.fcn(no2.df) # clean no2
o3.df <- aqi.fcn(o3.df) # clean o3

# include state abbreviations for plots
state.df <- data.frame(state.abb, state.name)
state.df <- state.df %>%  rename(State_Name = state.name)

# join with air pollutant datasets
no2.df <- left_join(no2.df, state.df, by = "State_Name")
o3.df <- left_join(o3.df, state.df, by = "State_Name")

# PR is left out, so do it separately
no2.df$state.abb <- ifelse(no2.df$State_Name == "Puerto Rico", "PR", no2.df$state.abb)
o3.df$state.abb <- ifelse(o3.df$State_Name == "Puerto Rico", "PR", o3.df$state.abb)

```


```{r,echo=F, warning=F, message=F}
##############
# create summary dfs
##############

# identify all monitoring stations in US
# monitor numbers can repeat, so need to remove duplicates by fips and monitor
no2.unique <- no2.df[!duplicated(no2.df[c(1,5)]), ] 
o3.unique <- o3.df[!duplicated(o3.df[c(1,5)]), ] 

# for every monitor in each county, identify the max daily aqi
no2.group <- no2.df %>% group_by(stcofips, Date_Local) %>%        arrange(desc(AQI), .by_group = T) %>%
                          summarize(maxAQI = max(AQI),
                          Site_Num = first(Site_Num),
                          State_Name = first(State_Name),
                          State_abb = first(state.abb),
                          County_Name = first(County_Name),
                          CBSA_Name = first(CBSA_Name),
                          Longitude = first(Longitude),
                          Latitude = first(Latitude))

# select aqi monitor with highest monthly average based on daily max aqi in each fips 
aqi.month.avg.high <- function(x){
x <- x %>% group_by(stcofips, month, Site_Num) %>% 
                          summarise(aqi_month_avg = mean(AQI),
                              State_Name = first(State_Name), # first in group, so okay bc will be the same for same monitor
                              State_abb = first(state.abb),
                              County_Name = first(County_Name),
                              CBSA_Name = first(CBSA_Name),
                              Longitude = first(Longitude),
                              Latitude = first(Latitude)) %>%
                          arrange(desc(aqi_month_avg), .by_group = T) %>% # select high
                          summarise(aqi_month_avg = first(aqi_month_avg),
                                    Site_Num = first(Site_Num), # why need this, shouldn't it be in the group?
                              State_Name = first(State_Name),
                              State_abb = first(State_abb),
                              County_Name = first(County_Name),
                              CBSA_Name = first(CBSA_Name),
                              Longitude = first(Longitude),
                              Latitude = first(Latitude),.groups = "keep")
return(x)
}

no2.high.co <- aqi.month.avg.high(no2.df)
o3.high.co <- aqi.month.avg.high(o3.df)

# identify the average monthly max aqi for each state
aqi.st.mo.high <- function(x) {x %>% group_by(State_Name, month) %>%
                arrange(desc(aqi_month_avg), .by_group = T) %>% 
                    summarise(max_month_avg = max(aqi_month_avg),
                              Site_Num = first(Site_Num),
                              State_abb = first(State_abb),
                              County_Name = first(County_Name),
                              CBSA_Name = first(CBSA_Name),
                              Longitude = first(Longitude),
                              Latitude = first(Latitude))
}

no2.high.st <- aqi.st.mo.high(no2.high.co)
o3.high.st <- aqi.st.mo.high(o3.high.co)

```

```{r monthly avg maps, echo=F, warning=F}

labels.no2 <- sprintf(
  "Location: %s <br/>  Site Number: %s",
  paste(no2.unique$County_Name, no2.unique$state.abb,  sep=", "),
  prettyNum(no2.unique$Site_Num)) %>% 
  lapply(htmltools::HTML)

labels.o3<- sprintf(
  "Location: %s <br/>  Site Number: %s",
  paste(o3.unique$County_Name, no2.unique$state.abb,  sep=", "),
  prettyNum(o3.unique$Site_Num)) %>% 
  lapply(htmltools::HTML)

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircles(data = no2.unique, group = "NO2 Air Pollutant 
             Monitors", color = "#E69F00", 
             highlightOptions = highlightOptions(color = "green", 
             weight = 2, bringToFront = TRUE),
             label = labels.no2,
             labelOptions = labelOptions(
             style = list("font-weight" = "normal", padding = "3px 8px"),
             textsize = "8px",
             direction = "auto")) %>%
    addCircles(data = o3.unique, group = "O3 Air Pollutant Monitors", color = "#56B4E9", 
             highlightOptions = highlightOptions(color = "green", 
             weight = 2, bringToFront = TRUE),
             label = labels.no2,
             labelOptions = labelOptions(
             style = list("font-weight" = "normal", padding = "3px 8px"),
             textsize = "8px",
             direction = "auto")) %>%
  addLayersControl(
    overlayGroups = c("NO2 Air Pollutant Monitors", "O3 Air Pollutant Monitors" ),
    options = layersControlOptions(collapsed = FALSE))
```


```{r, monthly avg plots, echo=F, warning=F, fig.height=5, fig.width=5}
# average monthly max AQI by state
# NO2
ggplot() + 
  geom_point(data = no2.high.st, aes(x=month, y=max_month_avg), alpha=.5, show.legend = FALSE) +
  labs(title = "Monthly Average NO2 Max AQI by State",x = "Month", y = "State Average NO2 max AQI")+
  facet_wrap(~State_abb)+
  theme_bw()+
theme(
      strip.text = element_text(size=10),
      axis.text = element_text(size =6),
      axis.title = element_text(size = 12))

# O3
ggplot() + 
  geom_point(data = o3.high.st, aes(x=month, y=max_month_avg), alpha=.5, show.legend = FALSE) +
  labs(title = "Monthly Average NO2 Max AQI by State",x = "Month", y = "State Average NO2 max AQI")+
  facet_wrap(~State_abb)+
  theme_bw()+
theme(
      strip.text = element_text(size=10),
      axis.text = element_text(size =6),
      axis.title = element_text(size = 12))
```


```{r, echo=F, warning=F, fig.height=5, fig.width=5}
# average monthly AQI by county
# NO3
ggplot() + 
  geom_point(data = no2.high.co, aes(x=month, y=aqi_month_avg), alpha=.5, show.legend = FALSE) +
  labs(title = "Monthly Average NO2 Max AQI for by County", x = "Month", y = "County Average NO2 max AQI")+
  facet_wrap(~State_abb)+
  theme_bw()+
theme(
      strip.text = element_text(size=10),
      axis.text = element_text(size =6),
      axis.title = element_text(size = 12))

# o3
ggplot() + 
  geom_point(data = o3.high.co, aes(x=month, y=aqi_month_avg), alpha=.5, show.legend = FALSE) +
  labs(title = "Monthly Average NO2 Max AQI for by County", x = "Month", y = "County Average NO2 max AQI")+
  facet_wrap(~State_abb)+
  theme_bw()+
theme(
      strip.text = element_text(size=10),
      axis.text = element_text(size =6),
      axis.title = element_text(size = 12))
```


```{r, echo=F, warning=F, fig.height=5, fig.width=5}
# data density for max AQI of all county sensors  
ggplot(data = no2.group, aes(x=State_abb, y=maxAQI)) + 
  geom_violin(show.legend = FALSE) +
  labs(title = "Data Concentration of Monthly Average NO2 Max AQI for All County Sensors", x = "State", y = "Avg NO2 max AQI",
       colour=NULL, shape=NULL) + 
  theme_bw()
```


```{r, echo=F, warning=F, fig.height=5, fig.width=5}
# idenfity CBSAs with highest max avg AQI
# NO2
top.no2 <- no2.high.co %>% group_by(CBSA_Name) %>% arrange(desc(aqi_month_avg), .by_group = T) %>% 
  filter(aqi_month_avg == first(aqi_month_avg)) %>% # to have only 1 record from each CBSA
  arrange(desc(aqi_month_avg))

top.no2 <-  top.no2[1:25, ] # select first 25, which are max

  ggplot(top.no2)+
  geom_col(aes(x=reorder(paste(CBSA_Name), aqi_month_avg), y=aqi_month_avg), show.legend = F) +
    coord_flip()+ 
  labs(x="City", y="Highest Monthly Avg Max AQI ", title ="Top 25 cities with NO2 pollution")+
  theme_minimal()
  
# o3
top.o3 <- o3.high.co %>% group_by(CBSA_Name) %>% arrange(desc(aqi_month_avg), .by_group = T) %>% 
  filter(aqi_month_avg == first(aqi_month_avg)) %>% # to have only 1 record from each CBSA
  arrange(desc(aqi_month_avg))

top.o3 <-  top.o3[1:25, ] # select first 25, which are max

top.o3$CBSA_Name <- ifelse(top.o3$County_Name == "Mariposa", "Mariposa, CA", top.o3$CBSA_Name) # Mariposa does not have a CBSA defined, so name it here

  ggplot(top.o3)+
  geom_col(aes(x=reorder(paste(CBSA_Name), aqi_month_avg), y=aqi_month_avg), show.legend = F) +
    coord_flip()+ 
  labs(x="City", y="Highest Monthly Avg Max AQI ", title ="Top 25 cities with O3 pollution")+
  theme_minimal()

```

```{r}
# max annual NO2 & O3 AQI recording by state
max.no2.high.co <- no2.high.co %>% group_by(CBSA_Name) %>%
  filter(aqi_month_avg == max(aqi_month_avg)) 

max.o3.high.co <- o3.high.co %>% group_by(CBSA_Name) %>%
  filter(aqi_month_avg == max(aqi_month_avg)) 

labels.no2<- sprintf(
  "Location: %s <br/>  Site Number: %s <br> Max Montly Avg AQI: %s <br> Month: %s",
  paste(max.no2.high.co$CBSA_Name, max.no2.high.co$state.abb,  sep=", "),
  prettyNum(max.no2.high.co$Site_Num),
  prettyNum(max.no2.high.co$aqi_month_avg),
  prettyNum(max.no2.high.co$month)) %>% 
  lapply(htmltools::HTML)

labels.o3<- sprintf(
  "Location: %s <br/>  Site Number: %s <br> Max Montly Avg AQI: %s <br> Month: %s",
  paste(max.o3.high.co$CBSA_Name, max.o3.high.co$state.abb,  sep=", "),
  prettyNum(max.o3.high.co$Site_Num),
  prettyNum(max.o3.high.co$aqi_month_avg),
  prettyNum(max.o3.high.co$month)) %>% 
  lapply(htmltools::HTML)

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircles(data = max.no2.high.co, group = "Monthly Avg Max NO2", color = "#E69F00", 
             highlightOptions = highlightOptions(color = "green", 
             weight = 2, bringToFront = TRUE),
             label = labels.no2,
             labelOptions = labelOptions(
             style = list("font-weight" = "normal", padding = "3px 8px"),
             textsize = "8px",
             direction = "auto")) %>%
  addCircles(data = max.o3.high.co, group = "Monthly Avg Max O3", color = "#56B4E9", 
             highlightOptions = highlightOptions(color = "green", 
             weight = 2, bringToFront = TRUE),
             label = labels.o3,
             labelOptions = labelOptions(
             style = list("font-weight" = "normal", padding = "3px 8px"),
             textsize = "8px",
             direction = "auto")) %>%
  addLayersControl(
    overlayGroups = c("Monthly Avg Max NO2", "Monthly Avg Max O3"),
    options = layersControlOptions(collapsed = FALSE))
```








```

```{r}
# maps for 03, what pct of NO2 sensors are active during year

```





