---
title: "lab3"
author: "Chris Samoray"
date: "2022-09-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(sf)
library(lubridate)
library(plotly)
library(gridExtra)
library(leaflet)
library(widgetframe)
```

```{r}
nyc.data <- read_csv(here("lab3", "data", "201806-citibike-tripdata.csv"))
names(nyc.data)

```

```{r}
nyc.data <- rename(nyc.data, #rename column names to get rid of the space
                   Slat = `start station latitude`,
                   Slon = `start station longitude`,
                   Elat = `end station latitude`,
                   Elon = `end station longitude`,
                   Sstid = `start station id`,
                   Estid = `end station id`,
                   Estname = `end station name`,
                   Sstname = `start station name`)

nyc.data


#Convert gender and usertype to factor
nyc.data$gender <- factor(nyc.data$gender, labels=c('Unknown', 'Male', 'Female')) 
nyc.data$usertype <- factor(nyc.data$usertype)
summary(nyc.data)

quantile(nyc.data$tripduration, .9)

prop.table(table(nyc.data$usertype))

prop.table(table(nyc.data$gender))

prop.table(xtabs(~usertype+gender, data=nyc.data), margin=2)
```

```{r}
start_loc <- unique(nyc.data[,c('Slon', 'Slat', "Sstid", 'Sstname')]) %>% rename(Longitude = Slon, Latitude = Slat, Stid = Sstid, Stname=Sstname)
end_loc <- unique(nyc.data[,c('Elon', 'Elat', 'Estid', 'Estname')]) %>% rename(Longitude = Elon, Latitude = Elat, Stid = Estid, Stname=Estname)
station_loc <- unique(rbind(start_loc, end_loc))
rm(start_loc, end_loc)


m1 <- 
leaflet(station_loc) %>%
  addProviderTiles(providers$Stamen.TonerLines, group = "Basemap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Basemap") %>%
  addMarkers(label = paste(station_loc$Stid, station_loc$Longitude, station_loc$Latitude, station_loc$Stname, sep=",")
  )

widgetframe::frameWidget(m1)
```

```{r}
(eightDstations <- station_loc[grep(glob2rx("8D*"), station_loc$Stname),]$Stid) # these are the outliers stations in MTL
nyc.data[which.max(nyc.data$tripduration), c('Sstname', 'Estname','tripduration')]
(Bikedepots <- station_loc[grep(glob2rx("*CBS*"), station_loc$Stname),]$Stid) # parenthesis at the start is to print
```
```{r}
nyc.data %>%
  select(Sstid, Estid, tripduration) %>%
  filter(tripduration >= 60*60*2) %>%
  group_by(Sstid, Estid) %>%
  summarise(triptots = n(),
            averagetripdur = mean(tripduration)
            ) %>%
  arrange(desc(triptots))

station_loc <- station_loc[!(station_loc$Stid %in% Bikedepots |  station_loc$Stid %in% eightDstations), ]
nyc.data <-  nyc.data[nyc.data$Estid %in% station_loc$Stid & nyc.data$Sstid %in% station_loc$Stid, ]
diffdesttrips <- nyc.data[nyc.data$Estid != nyc.data$Sstid, ]
c(nrow(nyc.data), nrow(diffdesttrips))
nrow(station_loc)

summary(diffdesttrips)

```

```{r, EXERCISE 1}

# explore for patterns in high values using date
test <- diffdesttrips %>% filter(tripduration > 10000)

# many outliers have trips lasting over a month; let's select trips completed within 24 hours
diffdesttrips$timediff <- diffdesttrips$stoptime - diffdesttrips$starttime
diffdesttrips <- diffdesttrips %>% filter(timediff <= 1440) # data is in mins, 1440 mins = 24 hrs

rm(test)
rm(nyc.data)

summary(diffdesttrips)
prop.table(table(diffdesttrips$usertype))
prop.table(table(diffdesttrips$gender))
summary(diffdesttrips$`birth year`)

# let's also remove birth years 100 or more years or less than 5 years old
diffdesttrips <- diffdesttrips %>% filter(`birth year`> 1920 & `birth year`< 2013)
```

```{r}
numtrips_start_station <- diffdesttrips %>%
  mutate(day_of_week = wday(starttime, label=TRUE, week_start=1)) %>% #create weekday variable from start time
  group_by(Sstid, day_of_week, usertype) %>%
  summarise(Slon = first(Slon),
            Slat = first(Slat),
            totaltrips = n()
            )

numtrips_start_station %>%
  arrange(desc(totaltrips))

g1 <- ggplot(numtrips_start_station) +
  geom_point(aes(x=Slon, y=Slat, size=totaltrips), alpha=.5) +  # We use the  size of the point to denote its attraction
   scale_size_continuous(range= c(.1,2))+
  facet_grid(usertype ~ day_of_week) +  # Compare subscribers and customers
   scale_x_continuous("", breaks=NULL)+
   scale_y_continuous("", breaks=NULL)+
   theme(panel.background = element_rect(fill='white',colour='white'), legend.position = "none")  + coord_fixed()

ggplotly(g1)

# ggplot(diffdesttrips, aes(Slon, Slat)) +  
#     stat_density2d(aes(alpha=..level.., fill=..level..), size=2, 
#         bins=10, geom="polygon") + 
#     scale_fill_gradient(low = "blue", high = "red") +
#     scale_alpha(range = c(0.00, 0.5), guide = FALSE) +
#     geom_density2d(colour="black", bins=10) 
```

```{r, EXERCISE 2}

# the visualization shows the distribution throughout the week of trips taken by subscribers and customers in NYC. Most trips are taken in Manhattan. However, subscribers take more trips in the outer boroughs than customers. There does not seem to be much difference of time the time of week when subscribers take trips. For customers, the weekend looks like it might be slightly more popular than other days of the week. 

diffdesttrips <- diffdesttrips %>% mutate(hr = hour(starttime))


trip.night <- diffdesttrips[diffdesttrips$hr > 20 | diffdesttrips$hr <= 4, ]

trip.morn <- diffdesttrips[diffdesttrips$hr > 4 & diffdesttrips$hr <= 12, ]

trip.day <- diffdesttrips[diffdesttrips$hr > 12 & diffdesttrips$hr <= 20, ]

# this is the most interesting, subscribers use bikes even in late hours, while customers do not as frequently
ggplot(trip.night) +
  geom_point(aes(x=Slon, y=Slat), alpha=.5) +  
   scale_size_continuous(range= c(.1,2))+
  labs(title = "Bike trips at night")+
  facet_grid(usertype ~ hr) +  # Compare subscribers and customers
   scale_x_continuous("", breaks=NULL)+
   scale_y_continuous("", breaks=NULL)+
   theme(panel.background = element_rect(fill='white',colour='white'), legend.position = "none")  + coord_fixed()


ggplot(trip.morn) +
  geom_point(aes(x=Slon, y=Slat), alpha=.5) +  
   scale_size_continuous(range= c(.1,2))+
  labs(title = "Bike trips in morning")
  facet_grid(usertype ~ hr) +  # Compare subscribers and customers
   scale_x_continuous("", breaks=NULL)+
   scale_y_continuous("", breaks=NULL)+
   theme(panel.background = element_rect(fill='white',colour='white'), legend.position = "none")  + coord_fixed()

# takes a long time to plot, and doesn't reveal much. Subscribers and customers use bikes throughout the day
# ggplot(trip.day) +
#   geom_point(aes(x=Slon, y=Slat), alpha=.5) +  
#    scale_size_continuous(range= c(.1,2))+
#   facet_grid(usertype ~ hr) +  # Compare subscribers and customers
#    scale_x_continuous("", breaks=NULL)+
#    scale_y_continuous("", breaks=NULL)+
#    theme(panel.background = element_rect(fill='white',colour='white'), legend.position = "none")  + coord_fixed()


```


```{r, Contour Plot}
ggplot(trip.night, aes(Slon, Slat)) +  
    stat_density2d(aes(alpha=..level.., fill=..level..), size=2, 
        bins=10, geom="polygon") + 
    scale_fill_gradient(low = "blue", high = "red") +
    scale_alpha(range = c(0.00, 0.5), guide = FALSE) +
    geom_density2d(colour="black", bins=10) 
```

```{r}
numtrips_start_station <- diffdesttrips %>%
  mutate(day_of_week = wday(starttime, label=TRUE, week_start=1)) %>%
  group_by(Sstid, day_of_week) %>%
  summarise(Slon = first(Slon),
            Slat = first(Slat),
            totaltrips = n()
            ) %>%
  group_by(day_of_week) %>%
   mutate(
     outlier_def = case_when(
       totaltrips <= quantile(totaltrips,.05) ~ "Low",
       totaltrips >= quantile(totaltrips, .95) ~ "High",
       TRUE ~ "Normal"
     )
   )

tmpfi <- numtrips_start_station %>% 
 filter(outlier_def!="Normal")

  g1 <- ggplot()+
  geom_point(aes(x=Slon, y=Slat, color=factor(outlier_def)), alpha=.9, data=tmpfi)+
  scale_color_brewer(palette="Dark2") + 
  labs(title = "Popularity of Start Station")+
  facet_wrap(~day_of_week, ncol=5)+
     scale_x_continuous("", breaks=NULL)+
   scale_y_continuous("", breaks=NULL)+
   theme(panel.background = element_rect(fill='white',colour='white'), legend.position = "bottom") +
  labs(colour = "Station Popularity") 
  
```


```{r, EXERCISE 3}
# popular at different times of day?
test <- diffdesttrips %>%
  group_by(Sstid, hr) %>%
  summarise(Slon = first(Slon),
            Slat = first(Slat),
            totaltrips = n()
            ) %>%
  group_by(hr) %>%
   mutate(
     outlier_def = case_when(
       totaltrips <= quantile(totaltrips,.05) ~ "Low",
       totaltrips >= quantile(totaltrips, .95) ~ "High",
       TRUE ~ "Normal"
     )
   )

tmpfi <- test %>% 
 filter(outlier_def!="Normal")

 ggplot()+
  geom_point(aes(x=Slon, y=Slat, color=factor(outlier_def)), alpha=.9, data=tmpfi)+
  scale_color_brewer(palette="Dark2") + 
  facet_wrap(~hr, ncol=8)+
     scale_x_continuous("", breaks=NULL)+
   scale_y_continuous("", breaks=NULL)+
   theme(panel.background = element_rect(fill='white',colour='white'), legend.position = "bottom") +
  labs(colour = "Station Popularity", title = "Popularity by Time of Day") 
 
# end destinations instead of start
test <- diffdesttrips %>%
  mutate(day_of_week = wday(stoptime, label=TRUE, week_start=1)) %>%
  group_by(Sstid, day_of_week) %>%
  summarise(Elon = first(Elon),
            Elat = first(Elat),
            totaltrips = n()
            ) %>%
  group_by(day_of_week) %>%
   mutate(
     outlier_def = case_when(
       totaltrips <= quantile(totaltrips,.05) ~ "Low",
       totaltrips >= quantile(totaltrips, .95) ~ "High",
       TRUE ~ "Normal"
     )
   )

tmpfi <- test %>% 
 filter(outlier_def!="Normal")

 g2 <- ggplot()+
  geom_point(aes(x=Elon, y=Elat, color=factor(outlier_def)), alpha=.9, data=tmpfi)+
  scale_color_brewer(palette="Dark2") + 
   labs(title = "Popularity of End Station")+
  facet_wrap(~day_of_week, ncol=5)+
     scale_x_continuous("", breaks=NULL)+
   scale_y_continuous("", breaks=NULL)+
   theme(panel.background = element_rect(fill='white',colour='white'), legend.position = "bottom") +
  labs(colour = "Station Popularity") 
 
grid.arrange(g1, g2, ncol = 2)
```
```{r, Spatial}
numtrips_start_station <- st_as_sf(numtrips_start_station, coords = c('Slon', 'Slat'), crs = 4326) # WGS84 coordinate system
 
head(numtrips_start_station)

 daytrips <-   numtrips_start_station[numtrips_start_station$day_of_week=="Tue",] # filter Tuesday
 center <- c((st_bbox(daytrips)$xmax+st_bbox(daytrips)$xmin)/2, (st_bbox(daytrips)$ymax+st_bbox(daytrips)$ymin)/2) 
 names(center) <- NULL
 
 # color palette
 Npal <- colorNumeric(
   palette = "Reds", n = 5,
   domain = daytrips$totaltrips
 )
 
 m1 <-daytrips %>%
    leaflet() %>%
  setView(lng=center[1], lat=center[2], zoom=13) %>%
  addProviderTiles(providers$Stamen.TonerLines, group = "Basemap") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Basemap") %>%
   addCircles(
     radius = (daytrips$totaltrips - mean(daytrips$totaltrips))/sd(daytrips$totaltrips) * 30,
     fillOpacity = .6,
    fillColor = Npal(daytrips$totaltrips),
     group = 'Stations',
     stroke=FALSE
   ) %>%
  addLegend("topleft", pal = Npal, values = ~totaltrips,
            labFormat = function(type, cuts, p) {
              n = length(cuts) 
              paste0(prettyNum(cuts[-n], digits=2, big.mark = ",", scientific=F), " - ", prettyNum(cuts[-1], digits=2, big.mark=",", scientific=F))
            },
            title = "Number of Trip Starts",
            opacity = 1
  )

 widgetframe::frameWidget(m1)
```

```{r}
st_distance(daytrips)[1:4,1:4]
st_buffer(st_transform(daytrips, crs=26917), dist=500)
daytrips %>% st_union() %>% st_centroid()
?st_union
?st_centroid
daytrips %>% st_union() %>% st_convex_hull() %>% plot()
?st_convex_hull

numtrips <- diffdesttrips %>%
  mutate(day_of_week = wday(starttime, label=TRUE, week_start=1),
         hr = hour(starttime),
         time_of_day = hr %>% cut(breaks=c(0,6,10,16,20,24), include.lowest = TRUE, labels=c("Midnight - 6AM", "6AM - 10AM", "10AM - 4PM", "4PM - 8PM", "8PM - Midnight"))
         ) %>%
  group_by(Sstid, Estid, day_of_week, time_of_day, gender) %>%
  summarise(Slon = first(Slon),
            Slat = first(Slat),
            Elon = first(Elon),
            Elat = first(Elat),
            totaltrips = n(),
            aveduration = mean(tripduration)
            )

numtrips %>% filter(totaltrips >2) %>%  
 ggplot()+
  #The "alpha=" is degree of transparency conditioned by totaltrips and used below to make the lines transparent
  geom_segment(aes(x=Slon, y=Slat,xend=Elon, yend=Elat, alpha=totaltrips, colour=gender))+
  #Here is the magic bit that sets line transparency - essential to make the plot readable
  scale_alpha_continuous(range = c(0.005, 0.5), guide='none')+
  #scale_color_manual(values=c('purple', 'white','green'), labels=c('Neither/Unknown', 'Male', "Female"), guide='legend')+
  scale_color_brewer(palette="Set1", guide='legend')+
  facet_grid(time_of_day~day_of_week)+
  #Set black background, ditch axes
  scale_x_continuous("", breaks=NULL)+
  scale_y_continuous("", breaks=NULL)+
  theme(panel.background = element_rect(fill='white',colour='white'), legend.position = "bottom")+
        #legend.key=element_rect(fill='black', color='black')) + 
  labs(title = 'New York Citi Bike June 2018 trips', colour="",caption="Nikhil Kaza: nkaza.github.io")
```

```{r}
numtrips <- diffdesttrips %>%
  mutate(day_of_week = wday(starttime, label=TRUE, week_start=1),
         hr = hour(starttime),
         time_of_day = hr %>% cut(breaks=c(0,6,10,16,20,24), include.lowest = TRUE, labels=c("Midnight - 6AM", "6AM - 10AM", "10AM - 4PM", "4PM - 8PM", "8PM - Midnight"))
         ) %>%
  group_by(Sstid, Estid, day_of_week, time_of_day, usertype) %>%
  summarise(Slon = first(Slon),
            Slat = first(Slat),
            Elon = first(Elon),
            Elat = first(Elat),
            totaltrips = n(),
            aveduration = mean(tripduration)
            )

numtrips %>% filter(totaltrips >2) %>%  
 ggplot()+
  #The "alpha=" is degree of transparency conditioned by totaltrips and used below to make the lines transparent
  geom_segment(aes(x=Slon, y=Slat,xend=Elon, yend=Elat, alpha=totaltrips, colour=usertype))+
  #Here is the magic bit that sets line transparency - essential to make the plot readable
  scale_alpha_continuous(range = c(0.005, 0.5), guide='none')+
  #scale_color_manual(values=c('purple', 'white','green'), labels=c('Neither/Unknown', 'Male', "Female"), guide='legend')+
  scale_color_brewer(palette="Set1", guide='legend')+
  facet_grid(time_of_day~day_of_week)+
  #Set black background, ditch axes
  scale_x_continuous("", breaks=NULL)+
  scale_y_continuous("", breaks=NULL)+
  theme(panel.background = element_rect(fill='white',colour='white'), legend.position = "bottom")+
        #legend.key=element_rect(fill='black', color='black')) + 
  labs(title = 'New York Citi Bike June 2018 trips', colour="",caption="Nikhil Kaza: nkaza.github.io")
```
```{r}

# The following code chunk only works if you have OSRM installed on the backend and the server is enabled. The OSRM package in R is an interface to it. I am showing the code only to show how you might create shortest paths using OSRM. You can skip it and move on to the next code chunk if you do not have OSRM installed.
# 
# library(osrm)
# unique_od_pairs <- diffdesttrips[!duplicated(diffdesttrips[,c('Sstid','Estid')]), c('Sstid', 'Slon', 'Slat', 'Estid', 'Elon', 'Elat')]
# options(osrm.server = "http://localhost:5000/", osrm.profile = "cycling")
# k <- osrmRoute(src=unique_od_pairs[i,c('Sstid', 'Slon', 'Slat')] , dst=unique_od_pairs[i,c('Estid','Elon','Elat')], overview = "full", sp = TRUE)
# 
# fastest_od_routes <- list()
# for(i in 1:nrow(unique_od_pairs)){
# try(fastest_od_routes[[i]] <- osrmRoute(src=unique_od_pairs[i,c('Sstid', 'Slon', 'Slat')] , dst=unique_od_pairs[i,c('Estid','Elon','Elat')], overview = "full", sp = TRUE))
# }
# 
# sapply(fastest_od_routes, is.null) %>% sum()
# 
# fastest_od_routes2 <- do.call(rbind, fastest_od_routes)
# writeOGR(fastest_od_routes2, dsn=".", layer="od_cycling_routes", driver="ESRI Shapefile")
```


```{r}
(od_fastest_routes <- here("lab3","data", "od_cycling_routes.shp") %>% read_sf())
(numtrips <- inner_join(numtrips, od_fastest_routes, by=c('Sstid' = 'src', "Estid"='dst')) %>% st_sf())
numtripsgt2 <- filter(numtrips, totaltrips>2)
here("lab3","data", "numtrips.shp") %>% write_sf(numtripsgt2, ., layer='numtrips.shp') # use dot in argument for file pathway
```

```{r, EXERCISE 4}

```

```{r}
(blks <- here("lab3","data", "nyc_blks.shp") %>% read_sf() )

station_loc <- station_loc %>% 
  st_as_sf(coords = c('Longitude', 'Latitude'), crs = 4326)

blks <- st_transform(blks, st_crs(station_loc)) # crs is same as station loc
blks %>% st_geometry() %>% plot()

blks <- blks %>% filter(ALAND10>0) # Ignore all the blocks that are purely water. This may be problematic for other analyses.
nrow(blks)

blks$BGID10 <- substr(blks$GEOID10, 1, 12)
bg <- blks %>% 
  group_by(BGID10) %>%
  summarise() # this automatically unions the geometry

bg %>% .[,1] %>% plot()

(bg <- bg %>% st_cast("MULTIPOLYGON"))

```

```{r}
bg_pop <- here("lab3","data", "nypop2016acs.csv") %>% read_csv()
bg_pop$GEOID10 <- stringr::str_split(bg_pop$GEOID, '15000US', simplify = TRUE)[,2]
bg_pop$GEOID10 %>% nchar() %>% summary()

bg_pop <- inner_join(bg_pop, bg, by=c("GEOID10"="BGID10")) %>% st_sf()
bg_pop %>% select(population, home_value) %>% plot(border=NA) # could also .[ , c(5,6)] instead of select
```
```{r}
# To create a visualisation that allows some dynamism, you can use mapview and leafsync packages. Mapview function quickly creates a leaflet like plot and sync function from leafsync allows you to link two plots together so that changes in one (zoom, pan etc) get reflected in the other. Use these to functions to recreate the above plot. Hint: use zcol argument

```


